project:
  type: website
  output-dir: docs

website:
  title: "Gil J. B. Henriques"
  navbar:
    left:
      - href: index.qmd
        text: ğŸ¡ Home
      - href: education.qmd
        text: ğŸ“ Education
      - href: research.qmd
        text: ğŸ“š Research
#      - href: cv.qmd
#        text: ğŸ“ƒ CV

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual